package com.KevinBonilla.Necromancer_fm.service.impl;

import com.KevinBonilla.Necromancer_fm.domain.CreateArtistRequest;
import com.KevinBonilla.Necromancer_fm.domain.entity.Artist;
import com.KevinBonilla.Necromancer_fm.repository.ArtistRepository;
import com.KevinBonilla.Necromancer_fm.service.ArtistService;
import org.springframework.stereotype.Service;

import java.time.Instant;

@Service
public class ArtistServiceImpl implements ArtistService {

    private final ArtistRepository artistRepository;

    public ArtistServiceImpl(ArtistRepository artistRepository) {
        this.artistRepository = artistRepository;
    }

    @Override
     public Artist createArtist(CreateArtistRequest request) {
        Instant now = Instant.now();

        Artist artist = new Artist(
                null, // specifying null here makes uuid autogenerated
                request.artistName(),
                request.playcount(),
                request.artistStatus(),
                now,
                now
        );

        return artistRepository.save(artist);
     }

}
